"""Initial schema

Revision ID: 655c094cb3c1
Revises: 
Create Date: 2026-01-26 20:18:59.515669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655c094cb3c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'query_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_foreign_key(None, 'agent_executions', 'queries', ['query_id'], ['id'])
    op.alter_column('billing_records', 'query_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.create_foreign_key(None, 'billing_records', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'billing_records', 'queries', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_records', type_='foreignkey')
    op.drop_constraint(None, 'billing_records', type_='foreignkey')
    op.alter_column('billing_records', 'query_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.alter_column('agent_executions', 'query_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
